## Traefik dynamic configuration
## Headers de segurança e TLS options

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: strict-origin-when-cross-origin
        customFrameOptionsValue: SAMEORIGIN

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
